#! /usr/bin/perl
use warnings;
use strict;
use lib qw(lib);
use DBI;
use DBIx::Perlish;
$DBIx::Perlish::Parse::DEVEL = 1;

my $dbh = DBI->connect("dbi:SQLite:");
$dbh->do("create table tbl (id int, name text)");

db_insert 'tbl', {
	id   => 1,
	name => 'hello',
}, {
	id   => 2,
	name => 'fefe',
}, {
	id   => 42,
	name => 'LIFF',
};

my $x = 2;
my $r = db_fetch { tbl->id / $x - 1 == 20 };
print "$DBIx::Perlish::SQL\n";
print "$r->{name}\n";
